### PR TITLE
Rename StaffRegisterBrowser.js to StaffRegisterBrowser.html

### PR DESCRIPTION
**Pull request by tydingsl**

### CODE REVIEW

**Comment by tydingsl** [comment]
When Greg submitted the original code, it passed the checks. But, he had it mislabeled as a js file instead of an html. The only change I made was in the name of the file, and now it doesn't pass the checks.

**Comment by tydingsl** [comment]
https://github.com/dewv/nlcAttendance/pull/48

**Comment by smattingly** [comment]
@brosekerg The form that you added needed to be a .html file, which Lauren has fixed. However, the file should not contain an entire HTML page, just the main portion of the page body. The `views\layouts\layout.html` file defines a "template" that your file's contents will get dropped into, so that all the stuff at page top and bottom are standard. 
After you change that, be sure to run `npm test`, which includes checks on HTML files. You will see some things that you need to modify because we weren't necessarily following the same standards in the past. For example, the CI build broke because some of the HTML was using single instead of double-quotes, and the checks rejected that.

**Comment by tydingsl** [comment]
Fixed on another branch

**Pull request closed without merging**
